declare module 'lucide-react' {
  import * as React from 'react'
  // Common icons used across the repo — typed as any to keep Batch 1 low-risk.
  export const Plus: React.ComponentType<any>
  export const Search: React.ComponentType<any>
  export const X: React.ComponentType<any>
  export const XCircle: React.ComponentType<any>
  export const XCircle2: React.ComponentType<any>
  export const Pause: React.ComponentType<any>
  export const AlertTriangle: React.ComponentType<any>
  export const Clock: React.ComponentType<any>
  export const Pill: React.ComponentType<any>
  export const AlertCircle: React.ComponentType<any>
  export const CheckCircle2: React.ComponentType<any>
  export const CheckCircle: React.ComponentType<any>
  export const PlayCircle: React.ComponentType<any>
  export const Play: React.ComponentType<any>
  export const StopCircle: React.ComponentType<any>
  export const Check: React.ComponentType<any>
  export const Loader2: React.ComponentType<any>
  export const LogIn: React.ComponentType<any>
  export const ChevronLeft: React.ComponentType<any>
  export const ChevronRight: React.ComponentType<any>
  export const ChevronDown: React.ComponentType<any>
  export const ChevronUp: React.ComponentType<any>
  export const List: React.ComponentType<any>
  export const Star: React.ComponentType<any>
  export const MapPin: React.ComponentType<any>
  export const Users: React.ComponentType<any>
  export const Tag: React.ComponentType<any>
  export const Edit3: React.ComponentType<any>
  export const Edit: React.ComponentType<any>
  export const Copy: React.ComponentType<any>
  export const MoreVertical: React.ComponentType<any>
  export const MoreHorizontal: React.ComponentType<any>
  export const PieChart: React.ComponentType<any>
  export const DownloadIcon: React.ComponentType<any>
  export const Download: React.ComponentType<any>
  export const FileText: React.ComponentType<any>
  export const Database: React.ComponentType<any>
  export const Pills: React.ComponentType<any>
  export const Receipt: React.ComponentType<any>
  export const FileDown: React.ComponentType<any>
  export const TrendingUp: React.ComponentType<any>
  export const TrendingDown: React.ComponentType<any>
  export const Package: React.ComponentType<any>
  export const BarChart3: React.ComponentType<any>
  export const Filter: React.ComponentType<any>
  export const FilterX: React.ComponentType<any>
  export const DollarSign: React.ComponentType<any>
  export const CheckSquare: React.ComponentType<any>
  export const Bell: React.ComponentType<any>
  export const BellRing: React.ComponentType<any>
  export const BellOff: React.ComponentType<any>
  export const Info: React.ComponentType<any>
  export const Zap: React.ComponentType<any>
  export const Gauge: React.ComponentType<any>
  export const Wifi: React.ComponentType<any>
  export const WifiOff: React.ComponentType<any>
  export const Circle: React.ComponentType<any>
  export const CheckCheck: React.ComponentType<any>
  export const Calendar: React.ComponentType<any>
  export const CalendarIcon: React.ComponentType<any>
  export const RefreshCw: React.ComponentType<any>
  export const CreditCard: React.ComponentType<any>
  export const Trash2: React.ComponentType<any>
  export const Paperclip: React.ComponentType<any>
  export const Eye: React.ComponentType<any>
  export const EyeOff: React.ComponentType<any>
  export const Target: React.ComponentType<any>
  export const Smartphone: React.ComponentType<any>
  export const Battery: React.ComponentType<any>
  export const ArrowRight: React.ComponentType<any>
  export const ArrowLeft: React.ComponentType<any>
  export const Home: React.ComponentType<any>
  export const Settings: React.ComponentType<any>
  export const Scan: React.ComponentType<any>
  export const Share2: React.ComponentType<any>
  export const User: React.ComponentType<any>
  export const UserPlus: React.ComponentType<any>
  export const History: React.ComponentType<any>
  export const Repeat: React.ComponentType<any>
  export const Flag: React.ComponentType<any>
  export const Trash: React.ComponentType<any>
  export const HelpCircle: React.ComponentType<any>
  export const LogOut: React.ComponentType<any>
  export const Upload: React.ComponentType<any>
  export const Palette: React.ComponentType<any>
  export const Shield: React.ComponentType<any>
  export const Lock: React.ComponentType<any>
  export const Monitor: React.ComponentType<any>
  export const Sun: React.ComponentType<any>
  export const Moon: React.ComponentType<any>
  export const Menu: React.ComponentType<any>
  export const Crown: React.ComponentType<any>
  export const Sparkles: React.ComponentType<any>
  export const Mic: React.ComponentType<any>
  export const Save: React.ComponentType<any>
  export const ShoppingCart: React.ComponentType<any>
  export const Droplet: React.ComponentType<any>
  export const Truck: React.ComponentType<any>
  export const Heart: React.ComponentType<any>
  export const Gamepad2: React.ComponentType<any>
  export const Book: React.ComponentType<any>

  // Fallback default export
  const _default: any
  export default _default
}
